In [1]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib. pyplot as plt
import pandas as pd
import numpy as np

In [2]:
from pyod.models.knn import KNN

In [3]:
credit_base = pd.read_csv('credit_risk_dataset.csv')
credit_base.drop(credit_base.columns[[2,3,4,5,7,9,10,11]], axis = 1, inplace=True)
credit_base.dropna(inplace=True)

In [4]:
credit_base.head(1)

person_age  person_income  loan_amnt  loan_status
0          22          59000      35000            1

In [7]:
detector = KNN()
detector.fit(credit_base.iloc [:,1:4])

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [8]:
predict = detector.labels_
predict

array([1, 0, 1, ..., 1, 0, 0])

In [9]:
np.unique(predict, return_counts = True)

(array([0, 1]), array([29345,  3236], dtype=int64))

In [10]:
predict_score = detector.decision_scores_
predict_score

array([4750.        ,  300.00166666, 1179.24721751, ..., 2000.        ,
          0.        ,   25.        ])

In [11]:
#exporting data

outliers = []
for i in range(len(predict)):
    if predict[i] == 1:
        outliers.append(i)

In [12]:
print(outliers)

[0, 2, 3, 4, 6, 7, 8, 11, 14, 15, 16, 17, 18, 20, 21, 22, 24, 25, 28, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 63, 64, 66, 67, 68, 69, 71, 73, 74, 76, 79, 80, 81, 82, 83, 85, 86, 87, 89, 90, 91, 92, 93, 94, 98, 99, 100, 101, 102, 103, 107, 108, 111, 112, 113, 114, 117, 121, 124, 125, 130, 134, 136, 137, 138, 139, 140, 141, 142, 143, 144, 149, 150, 158, 159, 160, 172, 174, 182, 184, 186, 187, 193, 196, 209, 210, 211, 212, 213, 216, 217, 221, 222, 223, 224, 232, 233, 234, 235, 236, 237, 238, 239, 242, 243, 244, 247, 248, 253, 254, 255, 263, 264, 280, 281, 282, 283, 296, 298, 299, 300, 301, 302, 309, 310, 311, 312, 313, 317, 332, 333, 334, 335, 336, 346, 347, 348, 349, 350, 354, 360, 361, 362, 363, 372, 381, 387, 388, 389, 392, 396, 398, 399, 400, 402, 403, 406, 407, 409, 411, 421, 423, 431, 438, 440, 445, 448, 452, 457, 460, 462, 463, 464, 466, 469, 470, 476, 477, 478, 479, 481, 482, 483, 485, 486, 487, 491, 493, 494, 495

In [13]:
outliers_list = credit_base.iloc[outliers,:]
outliers_list

person_age  person_income  loan_amnt  loan_status
0              22          59000      35000            1
2              25           9600       5500            1
3              23          65500      35000            1
4              24          54400      35000            1
6              26          77100      35000            1
...           ...            ...        ...          ...
32544          58         780000       4500            0
32546          60        1900000       1500            0
32551          58         780000       4500            0
32561          54         129000       9000            1
32578          65          76000      35000            1

[3236 rows x 4 columns]