In [1]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib. pyplot as plt
import pandas as pd
import numpy as np

In [2]:
house_df = pd.read_csv('house_prices.csv')

In [3]:
x_houses = house_df.iloc[:,3:19].values
x_houses

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [4]:
y_houses = house_df.iloc[:,2].values
y_houses

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [16]:
from sklearn.model_selection import train_test_split
x_houses_test, x_houses_train, y_houses_test, y_houses_train = train_test_split(x_houses, y_houses, train_size=0.3, random_state=0)


In [17]:
x_houses_test.shape, x_houses_train.shape

((6483, 16), (15130, 16))

In [18]:
y_houses_train.shape, y_houses_test.shape

((15130,), (6483,))

In [19]:
from sklearn.tree import DecisionTreeRegressor

In [21]:
regr_tree_hc = DecisionTreeRegressor()
regr_tree_hc.fit(x_houses_train, y_houses_train)

DecisionTreeRegressor()

In [22]:
regr_tree_hc.score(x_houses_train, y_houses_train)

0.9995828772771221

In [23]:
regr_tree_hc.score(x_houses_test, y_houses_test)

0.7584191707993105

In [25]:
predict_test = regr_tree_hc.predict(x_houses_test)
predict_test

array([405000., 864000., 601002., ..., 330000., 590000., 565000.])

In [26]:
y_houses_test

array([469000., 780000., 520000., ..., 431000., 411000., 699900.])

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [29]:
mean_absolute_error(y_houses_test,predict_test)

97637.65417245103

In [30]:
mean_squared_error(y_houses_test, predict_test)

30075550444.92403

In [31]:
np.sqrt(mean_squared_error(y_houses_test, predict_test))

173423.03896807952

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [32]:
x_houses_train

array([[ 2.00000e+00,  1.50000e+00,  1.43000e+03, ...,  9.81250e+04,
         4.77222e+01, -1.22290e+02],
       [ 4.00000e+00,  3.25000e+00,  4.67000e+03, ...,  9.80050e+04,
         4.76350e+01, -1.22164e+02],
       [ 2.00000e+00,  7.50000e-01,  1.44000e+03, ...,  9.81070e+04,
         4.76707e+01, -1.22364e+02],
       ...,
       [ 4.00000e+00,  2.75000e+00,  4.51000e+03, ...,  9.81170e+04,
         4.76852e+01, -1.22400e+02],
       [ 4.00000e+00,  2.75000e+00,  2.33000e+03, ...,  9.80230e+04,
         4.73203e+01, -1.22385e+02],
       [ 4.00000e+00,  3.00000e+00,  1.98000e+03, ...,  9.81330e+04,
         4.77513e+01, -1.22334e+02]])

In [33]:
y_houses_train

array([ 297000., 1578000.,  562100., ..., 1057000.,  299900.,  395000.])

In [37]:
regr_random_forest_houses = RandomForestRegressor(n_estimators = 100)
regr_random_forest_houses.fit(x_houses_train,y_houses_train)

RandomForestRegressor()

In [38]:
regr_random_forest_houses.score(x_houses_train, y_houses_train)

0.9820742509101441

In [44]:
regr_random_forest_houses.score(x_houses_test, y_houses_test)


0.874458359372723

In [48]:
predict_test = regr_random_forest_houses.predict(x_houses_test)
predict_test

array([457909.  , 805795.03, 495055.  , ..., 404000.88, 464523.87,
       605378.  ])

: 

In [47]:
y_houses_test

array([469000., 780000., 520000., ..., 431000., 411000., 699900.])

In [42]:
mean_absolute_error(y_houses_test,predict_test)

68060.8576591929