In [ ]:
#Used for text mining

#Associated with probability

    #examples: 
        #document separation
        #spam filtering

# Laplacian correction is used when there is a 0 probability in a dataset.

In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.naive_bayes import GaussianNB #normal distribution

In [2]:
#import csv
credit_risk_base = pd.read_csv('D:\python_training_projects\ML Curso\data\credit_risk.csv')

In [3]:
credit_risk_base

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

In [10]:
# transorm to numpy array
x_credit_risk = credit_risk_base.iloc[:,0:4].values

In [6]:
x_credit_risk

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [5]:
#transform to numpy array
y_credit_risk = credit_risk_base.iloc[:, 4].values

In [8]:
y_credit_risk

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [9]:
# define encoder to transform into numerical data
from sklearn.preprocessing import LabelEncoder
le_historia = LabelEncoder()
le_divida = LabelEncoder()
le_garantias = LabelEncoder()
le_renda = LabelEncoder()



In [11]:
from re import X


x_credit_risk[:,0] = le_historia.fit_transform(x_credit_risk[:,0])
x_credit_risk[:,1] = le_divida.fit_transform(x_credit_risk[:,1])
x_credit_risk[:,2] = le_garantias.fit_transform(x_credit_risk[:,2])
x_credit_risk[:,3] = le_renda.fit_transform(x_credit_risk[:,3])




In [12]:
x_credit_risk

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [13]:
import pickle 
with open('credit_risk_base.pkl', 'wb')as f:
    pickle.dump([x_credit_risk, y_credit_risk],f)

In [16]:
naive_cr = GaussianNB()
naive_cr.fit(x_credit_risk, y_credit_risk)

GaussianNB()

In [19]:
# associating
# historia boa(0), divida alta(0), garantia nenhuma(1), renda> 35(2)
#historia ruim(2), divida alta(0), garantia adequada(0), renda <15(0)

predict = naive_cr.predict([[0,0,1,2],[2,0,0,0]])

In [20]:
predict

array(['baixo', 'moderado'], dtype='<U8')

In [21]:
naive_cr.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [22]:
naive_cr.class_count_

array([6., 5., 3.])

In [23]:
naive_cr.class_prior_

array([0.42857143, 0.35714286, 0.21428571])