y = b0 + b1 * x1 + b2 * x1 ** 2 +  bn * x1 ** n 

In [17]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib. pyplot as plt
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
health_care_df2 = pd.read_csv('heath_care2.csv')
health_care_df2

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [6]:
x_health_care2 = health_care_df2.iloc[:, 0:1].values
y_health_care2 = health_care_df2.iloc[:, 1].values

In [7]:
x_health_care2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [8]:
y_health_care2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [27]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 2)
x_health_care2_poly = poly.fit_transform(x_health_care2)

In [30]:
x_health_care2_poly.shape

(10, 3)

In [28]:
x_health_care2_poly

array([[1.000e+00, 1.800e+01, 3.240e+02],
       [1.000e+00, 2.300e+01, 5.290e+02],
       [1.000e+00, 2.800e+01, 7.840e+02],
       [1.000e+00, 3.300e+01, 1.089e+03],
       [1.000e+00, 3.800e+01, 1.444e+03],
       [1.000e+00, 4.300e+01, 1.849e+03],
       [1.000e+00, 4.800e+01, 2.304e+03],
       [1.000e+00, 5.300e+01, 2.809e+03],
       [1.000e+00, 5.800e+01, 3.364e+03],
       [1.000e+00, 6.300e+01, 3.969e+03]])

In [29]:
x_health_care2_poly[0]

array([  1.,  18., 324.])

In [31]:
regr_poly = LinearRegression()
regr_poly.fit(x_health_care2_poly, y_health_care2)

LinearRegression()

In [32]:
#b0
regr_poly.intercept_

7133.836363636166

In [33]:
#b1
regr_poly.coef_

array([   0.        , -469.89393939,    7.82121212])

In [34]:
new = [[40]]

In [35]:
new = poly.transform(new)
new

array([[1.0e+00, 4.0e+01, 1.6e+03]])

In [36]:
regr_poly.predict(new)

array([852.01818182])

In [38]:
predict = regr_poly.predict(x_health_care2_poly)
predict

array([1209.81818182,  463.6969697 ,  108.63636364,  144.63636364,
        571.6969697 , 1389.81818182, 2599.        , 4199.24242424,
       6190.54545455, 8572.90909091])

In [40]:
grath = px.scatter(x = x_health_care2.ravel(), y = y_health_care2)
grath.add_scatter(x = x_health_care2.ravel(), y = predict, name = 'Regression')
grath.show()