In [25]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib. pyplot as plt
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [26]:
house_df = pd.read_csv('house_prices.csv')


In [40]:
x_houses = house_df.iloc[:,3:19].values
x_houses

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [41]:
y_houses = house_df.iloc[:,2].values
y_houses

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [42]:
from sklearn.model_selection import train_test_split
x_houses_test, x_houses_train, y_houses_test, y_houses_train = train_test_split(x_houses, y_houses, train_size=0.3, random_state=0)
x_houses_test.shape, x_houses_train.shape

((6483, 16), (15130, 16))

In [43]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)


In [44]:
x_houses_train_poly = poly.fit_transform(x_houses_train)
x_houses_test_poly = poly.fit_transform(x_houses_test)

In [45]:
x_houses_train_poly.shape, x_houses_test_poly.shape

((15130, 153), (6483, 153))

In [46]:
regr_house_poly = LinearRegression()
regr_house_poly.fit(x_houses_train_poly, y_houses_train)

LinearRegression()

In [47]:
regr_house_poly.score(x_houses_train_poly, y_houses_train)

0.8202400896032292

In [48]:
regr_house_poly.score(x_houses_test_poly,y_houses_test)

0.8051632304379897

In [54]:
predict_test = regr_house_poly.predict(x_houses_test_poly)
predict_test

array([459042.31736755, 892569.93774033, 477025.8572998 , ...,
       534591.86991119, 355479.4911499 , 540276.63237762])

In [50]:
y_houses_test

array([469000., 780000., 520000., ..., 431000., 411000., 699900.])

In [51]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [55]:
mean_absolute_error(y_houses_test,predict_test)

101433.89197635665

In [56]:
mean_squared_error(y_houses_test, predict_test)

24256159360.312172

In [57]:
np.sqrt(mean_squared_error(y_houses_test, predict_test))

155743.89028245112