Support Vector Machine

In [105]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib. pyplot as plt
import pandas as pd
import numpy as np

In [106]:
health_care_df2 = pd.read_csv('heath_care2.csv')

In [107]:
x_health_care2 = health_care_df2.iloc[:, 0:1].values
y_health_care2 = health_care_df2.iloc[:, 1].values

In [108]:
y_health_care2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

Linear Kernel

In [109]:
from sklearn.svm import SVR

In [110]:
regr_svr_health = SVR(kernel= 'linear')
regr_svr_health.fit(x_health_care2, y_health_care2)

SVR(kernel='linear')

In [111]:
grath = px.scatter(x = x_health_care2.ravel(), y = y_health_care2)
grath.add_scatter(x = x_health_care2.ravel(), y = regr_svr_health.predict(y_health_care2.reshape(-1,1)), name = 'Regression')
grath.show()

polinomial kernel

In [112]:
regr_svr_health_poly = SVR(kernel= 'poly', degree = 3)
regr_svr_health_poly.fit(x_health_care2, y_health_care2)

SVR(kernel='poly')

In [113]:
grath = px.scatter(x = x_health_care2.ravel(), y = y_health_care2)
grath.add_scatter(x = x_health_care2.ravel(), y = regr_svr_health_poly.predict(y_health_care2.reshape(-1,1)), name = 'Regression')
grath.show()

rbf kernel

In [147]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x_health_scaled = scaler_x.fit_transform(x_health_care2)
scaler_y = StandardScaler()
y_health_scaled = scaler_y.fit_transform(y_health_care2.reshape(-1, 1))

In [154]:
x_health_scaled

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [155]:
y_health_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [156]:
regressor_svr_houses_rbf = SVR(kernel='rbf')
regressor_svr_houses_rbf.fit(x_health_scaled, y_health_scaled.ravel())

SVR()

In [159]:
grath = px.scatter(x = x_health_scaled.ravel(), y = y_health_scaled.ravel())
grath.add_scatter(x = x_health_scaled.ravel(), y = regressor_svr_houses_rbf.predict(y_health_scaled.reshape(-1,1)), name = 'Regression')
grath.show()

## Neural Network

In [160]:
x_health_scaled 

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [161]:
y_health_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [166]:
from sklearn.neural_network import MLPRegressor
regr_ann_health = MLPRegressor(max_iter=1000)
regr_ann_health.fit(x_health_scaled, y_health_scaled.ravel())


MLPRegressor(max_iter=1000)

In [167]:
regr_ann_health.score(x_health_scaled, y_health_scaled)

0.9576282335646563

In [168]:
grath = px.scatter(x = x_health_scaled.ravel(), y = y_health_scaled.ravel())
grath.add_scatter(x = x_health_scaled.ravel(), y = regr_ann_health.predict(y_health_scaled.reshape(-1,1)), name = 'Regression')
grath.show()

In [173]:
new = [[40]]
new = scaler_x.transform(new)
new

array([[-0.03481553]])

In [176]:
scaler_y.inverse_transform(regr_ann_health.predict(new).reshape(-1, 1))

array([[1076.32832488]])