In [56]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib. pyplot as plt
import pandas as pd
import numpy as np
from sklearn.svm import SVR

In [57]:
house_df = pd.read_csv('house_prices.csv')

In [58]:
x_houses = house_df.iloc[:,3:19].values
y_houses = house_df.iloc[:,2].values

In [59]:
from sklearn.model_selection import train_test_split
x_houses_test, x_houses_train, y_houses_test, y_houses_train = train_test_split(x_houses, y_houses, train_size=0.3, random_state=0)

In [60]:
x_houses_train.shape, x_houses_test.shape

((15130, 16), (6483, 16))

In [61]:
y_houses_train.shape, y_houses_test.shape

((15130,), (6483,))

In [76]:
from sklearn.preprocessing import StandardScaler

In [77]:
scaler_x_houses = StandardScaler()
x_houses_train_scaled = scaler_x_houses.fit_transform(x_houses_train)

In [78]:
scaler_y_houses = StandardScaler()
y_houses_train_scaled = scaler_y_houses.fit_transform(y_houses_train.reshape(-1, 1))

In [65]:
x_houses_train.shape, x_houses_test.shape, y_houses_train.shape, y_houses_test.shape

((15130, 16), (6483, 16), (15130,), (6483,))

In [66]:
y_houses_train_scaled

array([[-0.65474091],
       [ 2.77898332],
       [ 0.05586041],
       ...,
       [ 1.3824413 ],
       [-0.64696745],
       [-0.39205162]])

In [79]:
x_houses_test_scaled = scaler_x_houses.transform(x_houses_test)
y_houses_test_scaled = scaler_y_houses.transform(y_houses_test.reshape(-1, 1))

In [80]:
x_houses_train_scaled.shape, x_houses_test.shape

((15130, 16), (6483, 16))

In [81]:
x_houses_test_scaled.shape, y_houses_test_scaled.shape

((6483, 16), (6483, 1))

rbf kernel

In [70]:
regressor_svr_houses = SVR(kernel= 'rbf')
#

In [71]:
regressor_svr_houses.fit(x_houses_train_scaled, y_houses_train_scaled.ravel())#matrix converted to vector

SVR()

In [72]:
regressor_svr_houses.score(x_houses_train_scaled, y_houses_train_scaled)

0.7906886428205282

In [83]:
regressor_svr_houses.score(x_houses_test_scaled, y_houses_test_scaled)

0.79347273813387

In [84]:
predict = regressor_svr_houses.predict(x_houses_test_scaled)

In [85]:
predict

array([-0.32101502,  0.76080736, -0.11910674, ..., -0.26832862,
       -0.40631639,  0.14853848])

In [86]:
y_houses_test_scaled

array([[-0.19369441],
       [ 0.639942  ],
       [-0.05698876],
       ...,
       [-0.29555352],
       [-0.34916358],
       [ 0.42523371]])

In [90]:
y_houses_test_inverse = scaler_y_houses.inverse_transform(y_houses_test_scaled.reshape(-1, 1))
predict_inverse = scaler_y_houses.inverse_transform(predict.reshape(-1, 1))

In [91]:
predict_inverse

array([[421501.22411974],
       [825090.5536447 ],
       [496825.99887228],
       ...,
       [441156.64006115],
       [389678.32635477],
       [596674.88140464]])

In [92]:
y_houses_test_inverse

array([[469000.],
       [780000.],
       [520000.],
       ...,
       [431000.],
       [411000.],
       [699900.]])

In [95]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(y_houses_test_inverse,predict_inverse)

81767.71529187578

Neural Network

In [99]:
from sklearn.neural_network import MLPRegressor

In [97]:
x_houses_train_scaled.shape, y_houses_train_scaled.shape

((15130, 16), (15130, 1))

In [98]:
x_houses_test_scaled.shape, y_houses_test_scaled.shape

((6483, 16), (6483, 1))

In [104]:
regr_ann_houses = MLPRegressor(max_iter = 1000, hidden_layer_sizes= (9,9))
regr_ann_houses.fit(x_houses_train_scaled, y_houses_train_scaled.ravel())


MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [105]:
regr_ann_houses.score(x_houses_train_scaled, y_houses_train_scaled)

0.8936483229095153

In [106]:
regr_ann_houses.score(x_houses_test_scaled, y_houses_test_scaled)

0.8629558769379664

In [108]:
predict = regr_ann_houses.predict(x_houses_test_scaled)
predict

array([-0.20320288,  0.88000538,  0.0206867 , ..., -0.33317641,
       -0.54085276,  0.1096517 ])

In [109]:
y_houses_test_scaled

array([[-0.19369441],
       [ 0.639942  ],
       [-0.05698876],
       ...,
       [-0.29555352],
       [-0.34916358],
       [ 0.42523371]])

In [115]:
y_houses_test_inverse = scaler_y_houses.inverse_transform(y_houses_test_scaled)
y_houses_test_inverse

array([[469000.],
       [780000.],
       [520000.],
       ...,
       [431000.],
       [411000.],
       [699900.]])

In [116]:
predict_inverse = scaler_y_houses.inverse_transform(predict.reshape(-1,1))
predict_inverse

array([[465452.72982788],
       [869559.08181422],
       [548977.94407578],
       ...,
       [416964.24271181],
       [339487.60504471],
       [582167.61217439]])

In [117]:
mean_absolute_error(y_houses_test_inverse,predict_inverse)

77745.4648279036