In [29]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

In [30]:
x_random, y_random = make_blobs(n_samples= 200, centers =5, random_state = 2)

In [31]:
x_random

array([[ -3.86106645,  -5.06356055],
       [ -1.68399423, -10.86599403],
       [  0.29465961,  -2.22244407],
       [ -3.94078011,  -4.12789615],
       [  2.78584241,  -1.72256547],
       [ -5.2878017 ,  -4.35360822],
       [ -6.56056876,   3.79425331],
       [ -5.72696063,   2.31848828],
       [ -1.74079115,  -1.89186666],
       [ -0.72304576,  -4.48039415],
       [ -0.27973607,  -9.86256788],
       [  1.60339364,  -0.87005525],
       [ -1.59361015,  -8.71046363],
       [ -4.11025869,  -3.81510393],
       [ -1.91478126,  -8.97307912],
       [ -2.38581355,  -3.95077122],
       [ -0.42556099,  -1.54532627],
       [ -2.7436469 ,  -3.81982605],
       [  2.15477105,  -0.9074741 ],
       [ -5.0871422 ,   1.75430064],
       [ -0.02816517,  -0.86115645],
       [ -5.91462846,   1.45158867],
       [ -4.1740753 ,  -5.24006543],
       [ -0.55342505,  -3.37620408],
       [ -7.10202721,   1.89748878],
       [ -2.55573663,  -5.72838238],
       [ -0.55961489,  -3.72230601],
 

In [32]:
y_random

array([4, 0, 1, 4, 1, 4, 3, 3, 2, 2, 0, 1, 0, 4, 0, 4, 1, 2, 1, 3, 1, 3,
       4, 1, 3, 4, 2, 3, 4, 3, 0, 4, 2, 4, 2, 1, 0, 3, 4, 0, 0, 4, 3, 3,
       2, 0, 0, 3, 3, 2, 0, 2, 0, 4, 1, 3, 0, 1, 4, 3, 2, 4, 1, 3, 1, 2,
       0, 1, 4, 1, 3, 1, 2, 1, 4, 4, 1, 4, 0, 1, 1, 4, 1, 2, 2, 2, 2, 3,
       0, 3, 3, 1, 0, 3, 0, 2, 3, 1, 1, 4, 3, 1, 0, 0, 0, 4, 4, 3, 2, 3,
       0, 2, 3, 2, 0, 1, 3, 0, 4, 0, 0, 2, 0, 1, 3, 2, 3, 2, 1, 4, 2, 1,
       2, 4, 4, 2, 1, 0, 3, 1, 4, 1, 1, 2, 3, 4, 1, 3, 2, 1, 1, 0, 0, 4,
       4, 2, 3, 4, 0, 0, 2, 2, 1, 3, 4, 0, 1, 2, 2, 4, 2, 1, 3, 4, 2, 2,
       4, 3, 0, 0, 0, 2, 4, 2, 3, 3, 2, 4, 1, 3, 0, 4, 3, 1, 0, 3, 0, 0,
       4, 2])

In [33]:
grath = px.scatter(x = x_random[:,0], y = x_random[:,1])
grath.show()

In [34]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(x_random)

KMeans(n_clusters=5)

In [35]:
labels = kmeans_blobs.predict(x_random)
labels

array([4, 2, 3, 4, 3, 4, 1, 1, 0, 0, 2, 3, 2, 4, 2, 0, 3, 0, 3, 1, 3, 1,
       4, 0, 1, 4, 0, 1, 4, 1, 2, 4, 0, 4, 0, 3, 2, 1, 4, 2, 2, 4, 1, 1,
       0, 2, 2, 1, 1, 0, 2, 0, 2, 4, 3, 1, 2, 3, 0, 1, 0, 4, 3, 1, 3, 0,
       2, 3, 4, 3, 1, 3, 0, 3, 4, 4, 3, 4, 2, 3, 3, 4, 3, 0, 0, 0, 4, 1,
       2, 1, 1, 3, 2, 1, 2, 0, 1, 3, 3, 4, 1, 3, 2, 2, 2, 0, 0, 1, 4, 1,
       2, 4, 1, 0, 2, 3, 1, 2, 0, 2, 2, 0, 2, 3, 1, 0, 1, 0, 3, 4, 0, 3,
       0, 4, 0, 0, 3, 2, 1, 3, 4, 3, 3, 4, 1, 4, 3, 1, 4, 3, 3, 2, 2, 4,
       4, 0, 1, 0, 2, 2, 0, 0, 3, 1, 4, 2, 3, 0, 0, 4, 0, 3, 1, 4, 0, 0,
       4, 1, 2, 2, 2, 0, 4, 0, 1, 1, 0, 0, 3, 1, 2, 4, 1, 3, 2, 1, 2, 2,
       4, 0])

In [36]:
center_clusters = kmeans_blobs.cluster_centers_
center_clusters

array([[-1.75072647, -3.24723447],
       [-6.0581989 ,  2.20604643],
       [-1.53989279, -9.34457927],
       [ 1.28830552, -1.25578948],
       [-3.71046727, -4.65894478]])

In [37]:
grath_1 = px.scatter(x =x_random[:,0], y = x_random[:,1], color = labels)
grath_2 = px.scatter(x =center_clusters[:,0], y = center_clusters[:,1], size = [2,2,2,2,2])
grath_3 = go.Figure(data = grath_1.data + grath_2.data)
grath_3.show()