In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
import pickle


In [13]:

with open('credit.pkl', 'rb') as f:
    x_credit_train, x_credit_test, y_credit_train, y_credit_test = pickle.load(f)

In [14]:
x_credit = np.concatenate((x_credit_train, x_credit_test), axis=0)
y_credit = np.concatenate((y_credit_train, y_credit_test), axis = 0)


In [15]:
random_forest = pickle.load(open('final_random_forest.sav', 'rb'))
tree = pickle.load(open('final_tree.sav', 'rb'))
knn = pickle.load(open('final_knn.sav', 'rb'))

In [24]:
new_variable = x_credit[0]
new_variable

array([-1.06090423, -0.50135143, -0.75757339])

In [30]:
new_variable = new_variable.reshape(1,-1)

In [31]:
new_variable, new_variable.shape

(array([[-1.06090423, -0.50135143, -0.75757339]]), (1, 3))

In [33]:
random_forest_answer = random_forest.predict(new_variable)
tree_answer = tree.predict(new_variable)
knn_answer = knn.predict(new_variable)

In [34]:
random_forest_answer, tree_answer, knn_answer

(array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64))

In [37]:
pay = 0
dont_pay = 0

if random_forest_answer[0] == 1:
    dont_pay += 1
else:
    pay += 1

if tree_answer[0] == 1:
    dont_pay += 1
else:
    pay += 1

if knn_answer[0] == 1:
    dont_pay += 1
else:
    pay += 1

if pay > dont_pay:
    print('client will pay loan')

elif  pay == dont_pay:
    print('draw')

else:
    print('client will not pay')

client will pay loan


Rejecting classifiers

In [38]:
probability_random_forest = random_forest.predict_proba(new_variable)
probability_tree = tree.predict_proba(new_variable)
probability_knn = knn.predict_proba(new_variable)


In [39]:
probability_random_forest,probability_tree,probability_knn

(array([[0.80428479, 0.19571521]]),
 array([[0.80769231, 0.19230769]]),
 array([[0.72, 0.28]]))

In [40]:
random_forest_trust = probability_random_forest.max()
tree_trust = probability_tree.max()
knn_trust = probability_knn.max()

In [41]:
random_forest_trust,tree_trust,knn_trust


(0.804284787051747, 0.8076923076923077, 0.72)

In [45]:
pay = 0
dont_pay = 0
minimum_trust = 0.80
algorithm = 0

if random_forest_trust >= minimum_trust:
    algorithm += 1
if random_forest_answer[0] == 1:
    dont_pay += 1
else:
    pay += 1

if tree_trust >= minimum_trust:
    algorithm += 1
if tree_answer[0] == 1:
    dont_pay += 1
else:
    pay += 1

if knn_trust >= minimum_trust:
    algorithm += 1
if knn_answer[0] == 1:
    dont_pay += 1
else:
    pay += 1

if pay > dont_pay:
    print(f'client will pay loan, based on {algorithm} algorithm')

elif  pay == dont_pay:
    print(f'draw,based on {algorithm} algorithm')

else:
    print(f'client will not pay, based on {algorithm} algorithm')

client will pay loan, based on 2 algorithm
